import { Component } from '@angular/core';

@Component({
  selector: 'app-lookingfordevelop',
  templateUrl: './lookingfordevelop.component.html',
  styleUrl: './lookingfordevelop.component.css'
})
export class LookingfordevelopComponent {

  names: any[] = ["Luisa Montes de Oca", "Daniel Soto García", "Carolina Martínez López", "Alejandro Torres Navarro", "María Rodríguez Sánchez", "Javier López Martínez", "Ana García Rodríguez", "Juan Pérez Martínez", "Laura Gómez Fernández"]
  comens: any[] = ["Desarrolladora Front-end apasionada por la creación de interfaces de usuario intuitivas y atractivas. Especializada en HTML, CSS y JavaScript, se destaca en la implementación de diseños creativos y responsivos. Luisa siempre busca mejorar la experiencia del usuario y está al tanto de las últimas tendencias en diseño web.",
    "Ingeniero de Software Full Stack con experiencia en el desarrollo de aplicaciones escalables y robustas. Especializado en tecnologías como Python, Django, React y Vue.js, Daniel disfruta resolviendo problemas complejos y optimizando el rendimiento del software. Con una mentalidad orientada al cliente, se asegura de que las soluciones entregadas cumplan con los requisitos y expectativas del usuario final.",
    "Científica de Datos apasionada por descubrir patrones y tendencias en conjuntos de datos complejos. Con experiencia en Python, R y herramientas de aprendizaje automático, como TensorFlow y scikit-learn, Carolina disfruta explorando y analizando datos para extraer información valiosa. Su habilidad para comunicar insights de manera clara y efectiva la convierte en un miembro valioso en cualquier equipo de análisis de datos.",
    "Ingeniero de Software especializado en desarrollo de aplicaciones móviles nativas para iOS. Con experiencia en Swift y Objective-C, Alejandro tiene un historial comprobado de crear aplicaciones intuitivas y de alto rendimiento que ofrecen una excelente experiencia de usuario. Apasionado por la innovación, siempre está buscando nuevas tecnologías y técnicas para mejorar sus habilidades y mantenerse al tanto de las últimas tendencias en desarrollo de aplicaciones móviles.",
    "Ingeniera de Seguridad Informática con experiencia en proteger sistemas contra ciberataques. Especializada en auditoría de sistemas y análisis forense, María está comprometida a garantizar la integridad y la seguridad de la información. Conocedora de las últimas amenazas y vulnerabilidades, trabaja diligentemente para implementar medidas de seguridad proactivas y mantenerse un paso adelante de los posibles atacantes.",
    "Ingeniero DevOps con experiencia en automatización de procesos de desarrollo, integración y despliegue continuo. Especializado en herramientas como Docker, Kubernetes y Jenkins, Javier se enfoca en mejorar la eficiencia y la calidad de los flujos de trabajo de desarrollo. Con una mentalidad orientada a la automatización, busca constantemente formas de optimizar los procesos y reducir el tiempo de comercialización.",
    "Desarrolladora Back-end con experiencia en la construcción de sistemas escalables y seguros. Especializada en Java, Spring Boot y bases de datos relacionales y no relacionales, Ana se destaca en el diseño e implementación de servicios robustos y eficientes. Apasionada por resolver problemas técnicos desafiantes, trabaja diligentemente para garantizar la fiabilidad y el rendimiento de los sistemas que desarrolla.",
    "Ingeniero de Software especializado en desarrollo de videojuegos. Con experiencia en Unity y Unreal Engine, Juan tiene un historial comprobado de crear experiencias de juego inmersivas y emocionantes. Apasionado por la narrativa y el diseño de juegos, se esfuerza por crear mundos virtuales que cautiven a los jugadores y los sumerjan en nuevas aventuras. Siempre está explorando nuevas tecnologías y técnicas para mejorar sus habilidades y llevar sus juegos al siguiente nivel.",
    "Ingeniera Front-end con pasión por la creación de interfaces de usuario innovadoras y dinámicas. Especializada en tecnologías web como HTML, CSS y JavaScript, Laura se destaca en la implementación de diseños creativos y funcionales. Con una sólida comprensión de las mejores prácticas de diseño web y experiencia de usuario, trabaja diligentemente para garantizar que las aplicaciones que desarrolla sean intuitivas y fáciles de usar. Apasionada por la tecnología y el diseño, está constantemente explorando nuevas herramientas y técnicas para mejorar sus habilidades y mantenerse al tanto de las últimas tendencias en desarrollo web."]

}
